% Taken from the paper "Visualization of communities in networks" 
% (http://netwiki.amath.unc.edu/VisComms/VisComms)

% This function gets the xy position of nodes in football network using
% ground truth community and Fruchterman and Reingold placement of
% communities and then Fruchterman-Reingold placement of nodes within
% communities.

% INPUTS 
% A: the adjacency matrix for the network
% gn: a vector of group numbers, i.e. every node that has the number 1 is
% in group 1
% epsilon: the accuracy at which you would like the algorithm to act; .01
% tends to work well
% seed: the number used in the random number generator for placing the
% communities, any four digit number will work
% factor1: the number to multiply the community coordinates by, 2 tends to
% work well,
% factor2: the number to multiply the node coordinates by within the
% community, 4 tends to work in most cases

% OUTPUTS 
% xynew: the vectors of the xy coordinates for each node in your network
% XY: the vectors of xy coordinates for the communties
% xyc: the cellarray of xy coordinates for the nodes within each community
% that are centered at zero.

cd ../ProcessingResult/;
file = "../Datasets/football_corrected.mat";
load(file);
A = triu(B,1) + triu(B,1)';
sortConferences =  sortrows(Conferences, 1);
true_gn = sortConferences(:,2)+1;
true_gn(true_gn==12) = 12;
true_gn(true_gn==13) = 12;
true_gn(true_gn==14) = 12;
true_gn(true_gn==15) = 12;
true_gn(true_gn==16) = 12;
true_gn(true_gn==17) = 12;
true_gn(true_gn==18) = 12;
true_gn(true_gn==19) = 12;

epsilon = 0.0001;
seed = 546790;
xynew = fruc_rein(A, epsilon, seed);
disp(xynew);

K = 15;
state = 0;
weight = 0;
subplot(1,2,1);
graphplot2D(xynew,A,weight,10,true_gn);
xlim([-2 0.15]) 
ylim([-2.1 -0.2])
set(gca,'XColor','none')
set(gca,'YColor','none')
title("Ground truth communities")
set(gca,'fontsize', 18)
gn = 1:K;

outfile = strcat("../SmallNetworks/GibbsSAGM/Result/football_corrected",num2str(state),"K",num2str(K),".mat");
load(outfile);
weight = Avg_w./sum(Avg_w,2);
new_col = zeros(1,K);
for i = 1:11
    nodes = find(true_gn == i);
    new_col(i) = find(sum(weight(nodes,:),1)==max(sum(weight(nodes,:),1)));
end

new_col(i+1:K) = setdiff(1:K,new_col);
weight = weight(:,new_col);
subplot(1,2,2);
graphplot2D(xynew,A,weight,10,gn');
xlim([-2.1 0.15]) 
ylim([-2.1 -0.2])
set(gca,'XColor','none')
set(gca,'YColor','none')
title("Communities generated by S-AGM")
set(gca,'fontsize', 18)

set(gcf, 'units','normalized','outerposition',[0 0 1 1]);
out_file = strcat('../Plots/Football',num2str(state),'K',num2str(K));
saveas(gcf, out_file, 'epsc');
saveas(gcf, out_file, 'jpeg');
saveas(gcf, out_file, 'fig');
